### ISSUE TITLE
Not recentering world shader nodes

### ISSUE THREAD

**Issue by williamchange** [Quackarooni/Recenter_Nodes_on_Save#1]
As title, the add-on doesn't seem to recenter world shader nodes. I am using Blender 3.0.1

https://github.com/Quackarooni/Recenter_Nodes_on_Save/assets/830253/af147c65-62d3-4539-a91e-bc8eafcd3cad

**Comment by Quackarooni** [comment]
Could confirm, working on a fix for it now.

**Comment by Quackarooni** [comment]
Yeah, so somehow I just missed adding world and linestyle shaders as I was gathering all nodetrees.
Thanks for the report, it should be fixed now by the latest commit.

https://github.com/Quackarooni/Recenter_Nodes_on_Save/assets/83491032/3e891c0f-ee40-4ae4-9251-8240e7203196
